{
 "title": "Loadrush Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, active as \"vu\" from virtual_user"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, \ncase \n  when (sum(success) + sum(failure) + sum(error_capture)) != 0 then sum(success) * 100 / (sum(success) + sum(failure) + sum(error_capture)) \n  else null\nend as \"success\",\ncase \n  when (sum(success) + sum(failure) + sum(error_capture)) = 0 then null \n  else sum(failure) * 100 / (sum(success) + sum(failure) + sum(error_capture)) \nend as \"failure\"\nfrom\n(\n  SELECT\n    time_bucket('1 seconds', response.time) as time, \n    case when response_success.success = 'true' then 1 else 0 end as success, \n    case when response_failure.failure = 'true' then 1 else 0 end as failure, \n    case when response.error_capture = 'true' then 1 else 0 end as error_capture\n  FROM \n   response\n  LEFT join\n   response_success\n  on (response.trace = response_success.trace)\n  LEFT join\n   response_failure\n  on (response.trace = response_failure.trace) \n  WHERE\n    $__timeFilter(response.time)\n) as response\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "select time, timing_wait, timing_dns, timing_tcp, timing_request, timing_download, timing_total from response"
    }
   ]
  },
  {
   "title": "Success / Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, count(success) as response, sum(success) as \"😀\", sum(failure) as \"😩\", sum(error_capture) as \"😱\" from\n(\n  SELECT\n    time_bucket('1 s', response.time) as time, \n    case when response_success.success = 'true' then 1 else 0 end as success, \n    case when response_failure.failure = 'true' then 1 else 0 end as failure, \n    case when response.error_capture = 'true' then 1 else 0 end as error_capture\n  FROM \n   response\n  LEFT JOIN\n   response_success\n  ON (response.trace = response_success.trace) \n  LEFT JOIN\n   response_failure\n  ON (response.trace = response_failure.trace) \n  WHERE\n    $__timeFilter(response.time)\n) as response\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, count(*) as \"rps\" from\n(\n  SELECT\n    $__timeGroupAlias(\"time\", 1s)\n  FROM request\n  WHERE\n    $__timeFilter(\"time\")\n) as request\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Throughput (RPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, count(*) as \"rpm\" from\n(\n  SELECT\n    $__timeGroupAlias(\"time\", 1m)\n  FROM request\n  WHERE\n    $__timeFilter(\"time\")\n) as request\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, count(*) as \"rspm\" from\n(\n  SELECT\n    $__timeGroupAlias(\"time\", 1m)\n  FROM response\n  WHERE\n    $__timeFilter(\"time\")\n) as response\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}