export enum Env {
  LOADRUSH_VU_POOL_SIZE = 'LOADRUSH_VU_POOL_SIZE',
  LOADRUSH_DURATION = 'LOADRUSH_DURATION',
  LOADRUSH_INFLUXDB_TAGS = 'LOADRUSH_INFLUXDB_TAGS',
  LOADRUSH_BASE_URL = 'LOADRUSH_BASE_URL',
  LOADRUSH_TEST_ID = 'LOADRUSH_TEST_ID',
  LOADRUSH_HTTP_MAX_SOCKETS = 'LOADRUSH_HTTP_MAX_SOCKETS',
  LOADRUSH_HTTP_ACTIVE_SOCKET_TIMEOUT = 'LOADRUSH_HTTP_ACTIVE_SOCKET_TIMEOUT',
  LOADRUSH_HTTP_FREE_SOCKET_TIMEOUT = 'LOADRUSH_HTTP_FREE_SOCKET_TIMEOUT',

  LOADRUSH_INFLUXDB_ORG = 'LOADRUSH_INFLUXDB_ORG',
  LOADRUSH_INFLUXDB_TOKEN = 'LOADRUSH_INFLUXDB_TOKEN',
  LOADRUSH_INFLUXDB_API = 'LOADRUSH_INFLUXDB_API',
  LOADRUSH_VERBOSE_METRICS = 'LOADRUSH_VERBOSE_METRICS',

  LOADRUSH_TIMESCALEDB_HOST = 'LOADRUSH_TIMESCALEDB_HOST',
  LOADRUSH_TIMESCALEDB_PORT = 'LOADRUSH_TIMESCALEDB_PORT',
}
