export enum Env {
  LOADFLUX_VU_POOL_SIZE = 'LOADFLUX_VU_POOL_SIZE',
  LOADFLUX_DURATION = 'LOADFLUX_DURATION',
  LOADFLUX_INFLUXDB_TAGS = 'LOADFLUX_INFLUXDB_TAGS',
  LOADFLUX_BASE_URL = 'LOADFLUX_BASE_URL',
  LOADFLUX_TEST_ID = 'LOADFLUX_TEST_ID',

  LOADFLUX_INFLUXDB_ORG = 'LOADFLUX_INFLUXDB_ORG',
  LOADFLUX_INFLUXDB_TOKEN = 'LOADFLUX_INFLUXDB_TOKEN',
  LOADFLUX_INFLUXDB_API = 'LOADFLUX_INFLUXDB_API',
  LOADFLUX_VERBOSE_METRICS = 'LOADFLUX_VERBOSE_METRICS',
}
